/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gassupply;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shaun
 */
public class Home extends javax.swing.JFrame {
    Connection con;
    static boolean first;
    /**
     * Creates new form Home
     */
    
    static{
        first = true;
    }
    
    public Home() {
        initComponents();
        
        if(Home.first){        
            try{
                Class.forName("oracle.jdbc.OracleDriver");
                JOptionPane.showMessageDialog(this, "Driver Loaded");
            
                    try{
                    con = DriverManager.getConnection("jdbc:oracle:thin:@ShaunAllanH:1521:orcl", "scott", "tiger");
                    JOptionPane.showMessageDialog(this, "Connected to Oracle Database");
                    Home.first = false;
                    }
                catch(SQLException ex){
                    Logger.getLogger(GasSupply.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
            catch(ClassNotFoundException ex){
                Logger.getLogger(GasSupply.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        siteButton = new javax.swing.JButton();
        locationButton = new javax.swing.JButton();
        processingFacilityButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        refinementListButton = new javax.swing.JButton();
        refineryButton = new javax.swing.JButton();
        prodButton = new javax.swing.JButton();
        storageButton = new javax.swing.JButton();
        shipmentButton = new javax.swing.JButton();
        marketButton = new javax.swing.JButton();
        employeesButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        ordersButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gas Supply Chain System Database");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Select table");

        siteButton.setBackground(new java.awt.Color(204, 255, 255));
        siteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        siteButton.setText("Drilling Site");
        siteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siteButtonActionPerformed(evt);
            }
        });

        locationButton.setBackground(new java.awt.Color(204, 255, 255));
        locationButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        locationButton.setText("Location");
        locationButton.setToolTipText("");
        locationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationButtonActionPerformed(evt);
            }
        });

        processingFacilityButton.setBackground(new java.awt.Color(204, 255, 255));
        processingFacilityButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        processingFacilityButton.setText("Processing Facility");
        processingFacilityButton.setToolTipText("");
        processingFacilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processingFacilityButtonActionPerformed(evt);
            }
        });

        processButton.setBackground(new java.awt.Color(204, 255, 255));
        processButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        processButton.setText("Process");
        processButton.setToolTipText("");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        refinementListButton.setBackground(new java.awt.Color(204, 255, 255));
        refinementListButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refinementListButton.setText("Refinement List");
        refinementListButton.setToolTipText("");
        refinementListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refinementListButtonActionPerformed(evt);
            }
        });

        refineryButton.setBackground(new java.awt.Color(204, 255, 255));
        refineryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refineryButton.setText("Refinery");
        refineryButton.setToolTipText("");
        refineryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refineryButtonActionPerformed(evt);
            }
        });

        prodButton.setBackground(new java.awt.Color(204, 255, 255));
        prodButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prodButton.setText("Production");
        prodButton.setToolTipText("");
        prodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodButtonActionPerformed(evt);
            }
        });

        storageButton.setBackground(new java.awt.Color(204, 255, 255));
        storageButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        storageButton.setText("Storage Facility");
        storageButton.setToolTipText("");
        storageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageButtonActionPerformed(evt);
            }
        });

        shipmentButton.setBackground(new java.awt.Color(204, 255, 255));
        shipmentButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shipmentButton.setText("Shipment");
        shipmentButton.setToolTipText("");
        shipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipmentButtonActionPerformed(evt);
            }
        });

        marketButton.setBackground(new java.awt.Color(204, 255, 255));
        marketButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        marketButton.setText("Market");
        marketButton.setToolTipText("");
        marketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketButtonActionPerformed(evt);
            }
        });

        employeesButton.setBackground(new java.awt.Color(204, 255, 255));
        employeesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeesButton.setText("Employees");
        employeesButton.setToolTipText("");
        employeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesButtonActionPerformed(evt);
            }
        });

        customersButton.setBackground(new java.awt.Color(204, 255, 255));
        customersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customersButton.setText("Customers");
        customersButton.setToolTipText("");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });

        ordersButton.setBackground(new java.awt.Color(204, 255, 255));
        ordersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordersButton.setText("Orders");
        ordersButton.setToolTipText("");
        ordersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButtonActionPerformed(evt);
            }
        });

        ordersButton1.setBackground(new java.awt.Color(255, 102, 102));
        ordersButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordersButton1.setForeground(new java.awt.Color(255, 255, 255));
        ordersButton1.setText("Exit");
        ordersButton1.setToolTipText("");
        ordersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(siteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(processingFacilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refinementListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refineryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ordersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(storageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(locationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(processingFacilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(refinementListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(storageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(shipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(employeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(marketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refineryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ordersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siteButtonActionPerformed
        // TODO add your hasndling code here:
        this.dispose();
        
        DrillingSite drillingSite = new DrillingSite();
        drillingSite.setVisible(true);
    }//GEN-LAST:event_siteButtonActionPerformed

    private void locationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Location location = new Location();
        location.setVisible(true);
    }//GEN-LAST:event_locationButtonActionPerformed

    private void prodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Production production = new Production();
        production.setVisible(true);
    }//GEN-LAST:event_prodButtonActionPerformed

    private void processingFacilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processingFacilityButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        ProcessingFacility processingFacility = new ProcessingFacility();
        processingFacility.setVisible(true);
    }//GEN-LAST:event_processingFacilityButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Process process = new Process();
        process.setVisible(true);
    }//GEN-LAST:event_processButtonActionPerformed

    private void refinementListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refinementListButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        RefinementList refinementList = new RefinementList();
        refinementList.setVisible(true);
    }//GEN-LAST:event_refinementListButtonActionPerformed

    private void refineryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refineryButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Refinery refinery = new Refinery();
        refinery.setVisible(true);
    }//GEN-LAST:event_refineryButtonActionPerformed

    private void storageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        StorageFacility storage = new StorageFacility();
        storage.setVisible(true);
    }//GEN-LAST:event_storageButtonActionPerformed

    private void shipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipmentButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Shipment shipment = new Shipment();
        shipment.setVisible(true);
    }//GEN-LAST:event_shipmentButtonActionPerformed

    private void employeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Employees emp = new Employees();
        emp.setVisible(true);
    }//GEN-LAST:event_employeesButtonActionPerformed

    private void marketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Market market = new Market();
        market.setVisible(true);
    }//GEN-LAST:event_marketButtonActionPerformed

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Customers customers = new Customers();
        customers.setVisible(true);
    }//GEN-LAST:event_customersButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Orders orders = new Orders();
        orders.setVisible(true);
    }//GEN-LAST:event_ordersButtonActionPerformed

    private void ordersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ordersButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customersButton;
    private javax.swing.JButton employeesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton locationButton;
    private javax.swing.JButton marketButton;
    private javax.swing.JButton ordersButton;
    private javax.swing.JButton ordersButton1;
    private javax.swing.JButton processButton;
    private javax.swing.JButton processingFacilityButton;
    private javax.swing.JButton prodButton;
    private javax.swing.JButton refinementListButton;
    private javax.swing.JButton refineryButton;
    private javax.swing.JButton shipmentButton;
    private javax.swing.JButton siteButton;
    private javax.swing.JButton storageButton;
    // End of variables declaration//GEN-END:variables
}
